// Generates a bundled manifest of system-design posts (metadata + headings).
//
// Why this exists: reading the content directory with `fs` at request time does
// not work on the Cloudflare Workers runtime, and even at build time the cwd is
// not guaranteed. This script runs in Node at build time, resolves paths
// relative to itself (not process.cwd()), and emits a plain .ts module that gets
// bundled into the app — so post discovery works identically everywhere.
//
// Run via `npm run posts:gen` (also wired into predev/prebuild). Commit the
// generated file so the manifest ships even if the host build skips prebuild.

import fs from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"
import matter from "gray-matter"
import GithubSlugger from "github-slugger"

const CONTENT_DIR = fileURLToPath(
  new URL("../src/content/system-design", import.meta.url),
)
const OUT_FILE = path.join(CONTENT_DIR, "posts.generated.ts")

function extractHeadings(content) {
  const slugger = new GithubSlugger()
  const headings = []
  let inFence = false

  for (const line of content.split("\n")) {
    if (/^\s*```/.test(line)) {
      inFence = !inFence
      continue
    }
    if (inFence) continue

    const match = /^(#{2,3})\s+(.+?)\s*#*\s*$/.exec(line)
    if (!match) continue

    const text = match[2]
      .replace(/\[([^\]]+)\]\([^)]*\)/g, "$1")
      .replace(/[*_`]/g, "")
      .trim()

    headings.push({ depth: match[1].length, text, slug: slugger.slug(text) })
  }

  return headings
}

function build() {
  const files = fs.existsSync(CONTENT_DIR)
    ? fs.readdirSync(CONTENT_DIR).filter((f) => f.endsWith(".mdx"))
    : []

  const posts = files
    .map((file) => {
      const slug = file.replace(/\.mdx$/, "")
      const raw = fs.readFileSync(path.join(CONTENT_DIR, file), "utf8")
      const { data, content } = matter(raw)
      return {
        slug,
        title: data.title ?? slug,
        date: data.date ?? "",
        excerpt: data.excerpt ?? "",
        tags: data.tags,
        draft: data.draft ?? false,
        headings: extractHeadings(content),
      }
    })
    // Stable order for clean diffs; runtime re-sorts by date.
    .sort((a, b) => a.slug.localeCompare(b.slug))

  const banner =
    "// AUTO-GENERATED by scripts/generate-posts.mjs — do not edit by hand.\n" +
    "// Run `npm run posts:gen` after adding or editing a post.\n\n"

  const types =
    "export interface GeneratedHeading {\n" +
    "  depth: number\n  text: string\n  slug: string\n}\n\n" +
    "export interface GeneratedPost {\n" +
    "  slug: string\n  title: string\n  date: string\n  excerpt: string\n" +
    "  tags?: string[]\n  draft: boolean\n  headings: GeneratedHeading[]\n}\n\n"

  const body = `export const allPosts: GeneratedPost[] = ${JSON.stringify(posts, null, 2)}\n`

  fs.writeFileSync(OUT_FILE, banner + types + body)
  console.log(`[posts] wrote ${posts.length} post(s) to ${path.relative(process.cwd(), OUT_FILE)}`)
}

build()
