// AUTO-GENERATED by scripts/generate-posts.mjs — do not edit by hand.
// Run `npm run posts:gen` after adding or editing a post.

export interface GeneratedHeading {
  depth: number
  text: string
  slug: string
}

export interface GeneratedPost {
  slug: string
  title: string
  date: string
  excerpt: string
  tags?: string[]
  draft: boolean
  headings: GeneratedHeading[]
}

export const allPosts: GeneratedPost[] = [
  {
    "slug": "_template",
    "title": "Post title",
    "date": "2026-06-07",
    "excerpt": "One-line summary shown on the index and used as the page description.",
    "tags": [
      "tag-one",
      "tag-two"
    ],
    "draft": true,
    "headings": [
      {
        "depth": 2,
        "text": "Requirements",
        "slug": "requirements"
      },
      {
        "depth": 2,
        "text": "A section heading",
        "slug": "a-section-heading"
      },
      {
        "depth": 3,
        "text": "A subsection",
        "slug": "a-subsection"
      },
      {
        "depth": 2,
        "text": "Wrap up",
        "slug": "wrap-up"
      }
    ]
  },
  {
    "slug": "design-a-url-shortener",
    "title": "Design a URL Shortener",
    "date": "2026-06-07",
    "excerpt": "Back-of-the-envelope numbers, the read/write split, key generation strategies, and the caching layer behind a TinyURL-style service.",
    "tags": [
      "storage",
      "caching",
      "scaling"
    ],
    "draft": false,
    "headings": [
      {
        "depth": 2,
        "text": "Requirements",
        "slug": "requirements"
      },
      {
        "depth": 2,
        "text": "Back-of-the-envelope",
        "slug": "back-of-the-envelope"
      },
      {
        "depth": 2,
        "text": "High-level architecture",
        "slug": "high-level-architecture"
      },
      {
        "depth": 2,
        "text": "Key generation",
        "slug": "key-generation"
      },
      {
        "depth": 2,
        "text": "The read path",
        "slug": "the-read-path"
      },
      {
        "depth": 2,
        "text": "Where it can go wrong",
        "slug": "where-it-can-go-wrong"
      }
    ]
  }
]
